### ISSUE TITLE
Database bad permission

### ISSUE THREAD

**Issue by acien101** [anarres-org/generic_docker_systemd#5]
On `./tasks/db-setup.yml:9` on `user: 1000:1000` cause bad permission error when starting container.

The situation was bumping from old version of `generic_docker_systemd` to a newest one.

```
[ERROR] Plugin 'Aria' registration as a STORAGE ENGINE faile
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [Note] InnoDB: Using Linux native AIO
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must b
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] Plugin 'InnoDB' init function returned error.
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE fai
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [Note] Plugin 'FEEDBACK' is disabled.
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] Could not open mysql.plugin table. Some plugins may
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] Unknown/unsupported storage engine: InnoDB
Oct 09 23:46:46 delta docker[24025]: 2019-10-09 21:46:46 0 [ERROR] Aborting
Oct 09 23:46:47 delta systemd[1]: docker.gitea-db.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by m0wer** [comment]
That line is not the problem. When configuring the database **for the first time** (*tasks/db-setup.yml* is run only if the database didn't exist previously) we should run the container as an unprivileged user that will be used later.

If the database volumes were already created and don't have the appropiate permissions (those which allow `1000:1000` to `rwx`), the database won't be able to start.

This could have happened when bumping up versions as you say, but there is nothing to do about it in the code. ¿Should we add a warning in the *README.md* or some docs? ¿Should we close this issue?
